-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE*30*((100-D.DISCOUNT_RATE)*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN 
(
    SELECT CAR_TYPE,DURATION_TYPE,DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%'
) D ON A.CAR_TYPE=D.CAR_TYPE 
WHERE A.CAR_TYPE IN ('세단','SUV') AND A.CAR_ID NOT IN
(
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE END_DATE>='2022-11-01' AND START_DATE<'2022-12-01'
)
HAVING FEE>=500000 AND FEE < 2000000
ORDER BY CAR_ID;

