-- 코드를 입력하세요
SELECT A.ID AS ID, A.NAME AS NAME, A.HOST_ID AS HOST_ID
FROM PLACES A
LEFT JOIN 
    (   
        SELECT HOST_ID, COUNT(HOST_ID) AS CNT
        FROM PLACES
        GROUP BY HOST_ID
    ) AS B
ON A.HOST_ID=B.HOST_ID 
WHERE B.CNT > 1;