-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT)TOTAL_SALES
FROM FOOD_PRODUCT A
LEFT JOIN FOOD_ORDER B ON A.PRODUCT_ID=B.PRODUCT_ID
WHERE YEAR(B.PRODUCE_DATE)=2022 AND MONTH(B.PRODUCE_DATE)=5
# WHERE B.PRODUCE_DATE>='2022-05-01' AND B.PRODUCE_DATE<'2022-06-01'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,PRODUCT_ID;