-- 코드를 입력하세요
WITH BEST_REVIEWER AS
(
SELECT MEMBER_ID, COUNT(*) CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY CNT DESC
LIMIT 1
) 

SELECT A.MEMBER_NAME, C.REVIEW_TEXT,C.REVIEW_DATE
FROM MEMBER_PROFILE A
LEFT JOIN BEST_REVIEWER B ON A.MEMBER_ID=B.MEMBER_ID
LEFT JOIN REST_REVIEW C ON A.MEMBER_ID=C.MEMBER_ID
WHERE B.CNT IS NOT NULL
ORDER BY REVIEW_DATE, REVIEW_TEXT;