-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01'  
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
) B
ON A.CAR_ID=B.CAR_ID
WHERE B.CAR_ID IS NOT NULL AND DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01' 
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;