-- 코드를 작성해주세요

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, 
C.SIZE-A.SIZE_OF_COLONY AS YEAR_DEV
,ID
FROM ECOLI_DATA A
LEFT JOIN 
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR
) C
ON YEAR(A.DIFFERENTIATION_DATE)=C.YEAR
ORDER BY YEAR, YEAR_DEV;