-- 코드를 작성해주세요
WITH MAX_FISH AS (
    SELECT ID, LENGTH, FISH_TYPE,RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RNK 
    FROM FISH_INFO
)

SELECT ID, FISH_NAME, LENGTH
FROM MAX_FISH
LEFT JOIN FISH_NAME_INFO ON MAX_FISH.FISH_TYPE=FISH_NAME_INFO.FISH_TYPE
WHERE RNK=1
ORDER BY ID;
